//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransferService_Console.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MoveData", ReplyAction="http://tempuri.org/IService1/MoveDataResponse")]
        string MoveData(string jsonMapping);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MoveData", ReplyAction="http://tempuri.org/IService1/MoveDataResponse")]
        System.Threading.Tasks.Task<string> MoveDataAsync(string jsonMapping);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MoveDataReport", ReplyAction="http://tempuri.org/IService1/MoveDataReportResponse")]
        string MoveDataReport(string jsonMapping, string jsonReportMapping);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MoveDataReport", ReplyAction="http://tempuri.org/IService1/MoveDataReportResponse")]
        System.Threading.Tasks.Task<string> MoveDataReportAsync(string jsonMapping, string jsonReportMapping);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DataTransferService_Console.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DataTransferService_Console.ServiceReference1.IService1>, DataTransferService_Console.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string MoveData(string jsonMapping) {
            return base.Channel.MoveData(jsonMapping);
        }
        
        public System.Threading.Tasks.Task<string> MoveDataAsync(string jsonMapping) {
            return base.Channel.MoveDataAsync(jsonMapping);
        }
        
        public string MoveDataReport(string jsonMapping, string jsonReportMapping) {
            return base.Channel.MoveDataReport(jsonMapping, jsonReportMapping);
        }
        
        public System.Threading.Tasks.Task<string> MoveDataReportAsync(string jsonMapping, string jsonReportMapping) {
            return base.Channel.MoveDataReportAsync(jsonMapping, jsonReportMapping);
        }
    }
}
